### ISSUE TITLE
Mod conflict with Extra Utilities

### ISSUE THREAD

**Issue by pcmean** [abused/SuperOres#6] opened 2018-12-19 20:24 UTC
The game crashes when using only extra utils and superores.

### Game info:
MC Version: 1.12.2
Forge Version: forge-144.23.5.2796
SuperOres Version: superores-1.9.0-1.12.jar 
Extra Utils Version: extrautils2-1.12-1.9.8.jar  

### Crash Log:
---- Minecraft Crash Report ----
// There are four lights!

Time: 12/19/18 12:13 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from SuperOres (superores)
Caused by: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at net.minecraft.util.NonNullList.get(SourceFile:44)
	at abused_master.superores.blocks.BlockOreBase.<init>(BlockOreBase.java:66)
	at abused_master.superores.registry.ModResources.register(ModResources.java:32)
	at abused_master.superores.proxy.CommonProxy.preInit(CommonProxy.java:22)
	at abused_master.superores.proxy.ClientProxy.preInit(ClientProxy.java:23)
	at abused_master.superores.SuperOres.preinit(SuperOres.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 617924488 bytes (589 MB) / 961019904 bytes (916 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2796 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID          | Version      | Source                        | Signature                                |
	|:----- |:----------- |:------------ |:----------------------------- |:---------------------------------------- |
	| LCH   | minecraft   | 1.12.2       | minecraft.jar                 | None                                     |
	| LCH   | mcp         | 9.42         | minecraft.jar                 | None                                     |
	| LCH   | FML         | 8.0.99.99    | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge       | 14.23.5.2796 | forge-1.12.2-14.23.5.2796.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | extrautils2 | 1.0          | extrautils2-1.12-1.9.8.jar    | None                                     |
	| LCE   | superores   | 1.9.0_1.12   | superores-1.9.0-1.12.jar      | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 398.82' Renderer: 'GeForce GTX 1080/PCIe/SSE2'

**Comment by pcmean** [comment] 2018-12-19 20:36
It dose **NOT** crash with the previous version of the mod
MC Version: 1.12.2
Forge Version: forge-144.23.5.2796
SuperOres Version: superores-~~1.9.0~~ **1.8.4**-1.12.jar
Extra Utils Version: extrautils2-1.12-1.9.8.jar

**Comment by Celdecea** [comment] 2019-01-15 23:15
[Offending line](https://github.com/abused/SuperOres/blob/27366c3015da355d0d1e2eb62c72c19cab5677d5/src/main/java/abused_master/superores/blocks/BlockOreBase.java#L66). It looks to me like _.get(0)_ is being called without checking to see if the [return from _getOres()_](https://github.com/MinecraftForkage/MinecraftForkage/blob/b8b345c19bab9641e62234fec355a4f54ab86681/core/new-src/net/minecraftforge/oredict/OreDictionary.java#L455) is empty first, which should be a common practice.

Duplicate of #5 and same problem was present for #2.

**Comment by team-5678** [comment] 2019-01-16 18:53
so its fixed?

**Comment by pcmean** [comment] 2019-01-16 18:54
so it's fixed?

**Comment by Celdecea** [comment] 2019-01-16 21:58
> so it's fixed?

Sorry, I am not on this project. I was shopping around for a dense ores mod and I noticed three related issues. The info I posted was just what I saw as the problem.

The dev seems to be otherwise active on github so if he finds time it _should_ be a trivial fix. I know enough not to say it _will_ be, but it definitely _should_ be.

**Comment by pcmean** [comment] 2019-01-16 22:20
Okay well I can tell you that the previous version like I said before works wonderfully I would give it a try

**Comment by Shibva** [comment] 2019-02-16 01:29
OI
same issue here

heres a Log of it from my massive 305 some modpack for 1.12.2

https://gist.github.com/SteamDoge9000/999bc94a388d49d62b8c942c54e8fc29
(srry if its messy)

**Closed as completed** 2022-01-18 04:21 UTC
